Refactoring/week2
29th-WE-SOPT-Android-Part/Android-Kangmin pull request #8
Opened 2022-01-25 16:28 UTC by kkk5474096

2022-01-26 06:30 UTC, l2hyunwoo requested changes
우선 여기까지 한번 보고 반영해줘!

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/adapter/FollowerListAdapter.kt
> +            }
이 부분을 onBindViewHolder에서 수행되고 있는건 이 함수가 호출될때마다 touchListener가 새롭게 set 된다고도 볼 수 있겠네? 뷰홀더는 한번 만들어지고 그 이후로는 계속 재사용될텐데 그때 한번 행동을 정의하고 사용한다면 불필요한 함수호출을 막을 수 있을 것 같아

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/adapter/FollowerListAdapter.kt
> +        this.dragListener = listener
이런 setter를 달아두는 것도 좋은데 자바에서 주로 사용되는 패턴이야. 자바에서는 primary constructor 개념이 없어서 클래스 내부에 멤버 필드를 만들고 이 값을 변경하기 위해서 setter/getter를 만들자나! 한번만 set해서 사용할 것이라면 primary constructor를 활용해서 불필요한 코드를 줄이는 것도 좋을 것 같아

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/adapter/FollowerListAdapter.kt
> +        fun onClick(data: ResponseUser)
함수형 인터페이스 사용하는 건 좋은 것 같아

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/adapter/RepoListAdapter.kt
> +//    }
불필요한 주석은 삭제!

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/adapter/RepoListAdapter.kt
> +        val DIFFUTIL = object : DiffUtil.ItemCallback<ResponseRepo>() {
외부에서 안 사용하는 변수라면 private으로 걸어잠구는게 좋아!

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/api/data/response/ResponseUser.kt
> +    var id: Int,
이건 가변변수로 바꾼 이유가 있을까?

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/util/MyTouchHelperCallback.kt
> +        }
디양한 레이아웃 매니저가 있을 수 있는데 이걸 if-else문으로 퉁친 것 같아서 확장성이 떨어져보여, 다양한 경우의 수를 어떻게 처리할 수 있는 지에 대해서 kotlin 자체 문법에 있는 내용하고 디자인 패턴 중에 전략(혹은 상태) 패턴을 한번 살펴보고 적용하는 것도 좋을 것 같아

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +    private val binding get() = _binding!!
지금 여러 Fragment에서 동일한 코드가 재사용되고 있는데 이걸 공통적으로 처리해주면 좋지 않을까?

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +        val repoListFragment = RepoListFragment()
어차피 아래에서 Fragment를 생성시킬건데 여기다가 임시변수를 둔 의도를 잘 모르겠어

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +    private fun changeFragment() {
이 함수는
- UI상태 변경 + 프래그먼트를 생성하고
- viewModel에 Fragment를 set하는 트리거를 보내주고
- 그 상태를 observe하고

있네, 한 함수에 여러 기능들이 복합적으로 있어서 통일감이 보여지지 않는 것 같아 이 부분 한 번 다시 봐줄 수 있겠어?

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +            viewModel.setFalseFragment()
setFragment와 setFalseFragment는 어떤 동작을 하는 건지 함수명만으론 감이 안와. Fragment에서 false를 할 수 있는 것이 무엇이지? 코드를 보는 입장에서 구현부의 코드를 직접 보고 이해를 해야하고 나중에 형이 이 코드를 볼때도 충분히 헷갈려할 수 있을 것 같아서 수정이 필요할 것 같아

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +            }
둘이 동일한 구조로 묶인 것 같은데 잘 묶어보면 코드를 묶을 수 있지 않을까?

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +    }
이부분도 마찬가지

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileViewModel.kt
> +    }
이것도 지난번에 리뷰에서 잠깐 다뤘던 것 같은데 버튼 클릭을 하고 난 뒤에 행위를 다루는 거여서 SingleLiveEvent나 Event Wrapper를 사용하는게 더 적당할 수 있을 것 같아

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/follow/FollowerListFragment.kt
> +        val intent = Intent(requireContext(), DetailActivity::class.java).apply {
- 멤버변수에서 requireContext사용하면 예상치 못한 오류가 터질 수 있어. requireContext는 Fragment의 onAttach 이후부터 사용할 수 있는 건데 Fragment 객체가 생성되는 건 그 이전이거든(Fragment의 생성과 onAttach 함수 호출은 전혀 별개의 것입니다)
- adapter 역시 View에 붙어있는 객체여서 이것도 binding처럼 onDestroyView에서 null로 바꿔줘야 메모리 릭이 발생안해, 그래서 ``private var adapter: FollowerListAdapter? = null``로 사용하고 onViewCreated에서 초기화해주는 로직이 좀 더 좋을 것 같아

2022-01-26 06:30 UTC, l2hyunwoo commented on app/src/main/res/layout/fragment_follwer_list.xml
> +            app:layout_constraintRight_toRightOf="parent"
layout_width가 match_parent면 굳이 constraint를 지정안해도 될 것 같아. 그리고 안드로이드 os의 접근성 향상을 위해서 left, right보단 start, end를 사용하는게 더 좋아

2022-01-26 16:29 UTC, l2hyunwoo requested changes
수고해쓰!

2022-01-26 16:29 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +            }
이 부분은 조금 더 줄일 수 있을 것 같아!

2022-01-26 16:29 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/repo/RepoListFragment.kt
> +        adapter = null
이건 super.onDestroyView() 이전에 호출되는게 더 안전해. super.onDestroyView가 부모클래스의 소멸자 역할한다고 생각하면 됨

2022-01-26 16:29 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/fragment/BoardingFragment1.kt
> +        super.onCreateView(inflater, container, savedInstanceState)
그냥 onCreateView 지워도 될 것 같아요!

2022-01-26 16:29 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/fragment/BoardingFragment2.kt
> +        super.onCreateView(inflater, container, savedInstanceState)
여기도

2022-01-26 16:29 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/fragment/BoardingFragment3.kt
> +        super.onCreateView(inflater, container, savedInstanceState)
여기도!

2022-01-26 16:29 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/CameraFragment.kt
> +        super.onCreateView(inflater, container, savedInstanceState)
여기도!

2022-01-26 16:29 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +            Glide.with(this).load(it).circleCrop().into(binding.ivProfile)
이부분을 봤을 때 profileImage라는 함수명이 어떤 역할을 할 지 잘 모르겠어, 함수의 기능을 분명히 해줘야할 것 같아! 만약에 아래의 기능들을 보면서 특정지을 수 없다면 하나의 함수에서 하나의 기능을 담당하고 있는 지 다시 확인해줘. 그래야 함수명을 더 잘 지을 수 있거든

2022-01-26 16:29 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +    }
fragmentManager라는 함수 이름이 아래의 기능과 한방에 매치가 될까? 함수 이름만 보고 어떤 역할을 할 지 예상이 안가

2022-01-27 06:46 UTC, l2hyunwoo approved these changes
머지 가즈아

2022-01-27 06:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/ProfileFragment.kt
> +    private fun buttonColor(isSelect: Boolean) {
이부분 추가 첨언: 좀 더 명확하게 하기 위해서 isFollowSelected 정도도 괜찮을 것 같긴 해! 이건 다음에 반영하면 더 좋을 것 같음

2022-01-27 06:46 UTC, l2hyunwoo commented on app/src/main/java/org/sopt/soptandroidseminar/view/main/profile/follow/FollowerListFragment.kt
> +            val intent = Intent(requireActivity(), DetailActivity::class.java).apply {
```suggestion
            val intent = Intent(requireContext(), DetailActivity::class.java).apply {
```

이정도만 들어가도 충분해

2022-01-28 08:23 UTC, papajj06 approved these changes
LGTM👍

2022-01-28 08:25 UTC, merged